version: "3"

services:
  reverse-proxy:
    image: traefik:v2.9
    command: --configFile=/etc/config/traefik.yml
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dynamic.yml:/etc/config/traefik-config.yml
      - ./static.yml:/etc/config/traefik.yml
      - ./plugins-local:/plugins-local
  wake:
    image: rix1337/docker-wol_api
    network_mode: host
    environment:
      - PORT=8081

networks:
  traefik: